import { BarData } from '../components/ui/BarCard';

const barImages = {
  horseYouCameInOn: require('../assets/images/bars/horse-you-came-in-on.jpeg'),
  catsEyePub: require('../assets/images/bars/cats-eye-pub.jpeg'),
  recPier: require('../assets/images/bars/rec-pier.jpeg'),
  federalHillBrewing: require('../assets/images/bars/federal-hill-brewing.jpeg'),
  banditos: require('../assets/images/bars/banditos.jpeg'),
  noWayJose: require('../assets/images/bars/no-way-jose.jpeg'),
  cantonSocial: require('../assets/images/bars/canton-social.jpeg'),
  rustyAnchor: require('../assets/images/bars/rusty-anchor.jpeg'),
  powerPlantLive: require('../assets/images/bars/power-plant-live.jpeg'),
  federalRooftop: require('../assets/images/bars/federal-rooftop.jpeg'),
  maximon: require('../assets/images/bars/maximon.jpeg'),
  brewersArt: require('../assets/images/bars/brewers-art.jpeg'),
  ottobar: require('../assets/images/bars/ottobar.jpeg'),
  clubCharles: require('../assets/images/bars/club-charles.jpeg'),
  goldenWest: require('../assets/images/bars/golden-west.jpeg'),
  theDizz: require('../assets/images/bars/the-dizz.jpeg'),
  unionCraft: require('../assets/images/bars/union-craft.jpeg'),
  wetCity: require('../assets/images/bars/wet-city.jpeg'),
  stickyRice: require('../assets/images/bars/sticky-rice.jpeg'),
  elkRoom: require('../assets/images/bars/elk-room.jpeg'),
};

export interface Bar {
  id: string;
  name: string;
  neighborhood: string;
  vibe: string;
  emoji: string;
  color: string;
  currentCrowd: number;
  activeSpecial?: string;
  badgeEmoji?: string;
  badgeRarity?: 'COMMON' | 'RARE' | 'EPIC' | 'LEGENDARY';
  address: string;
  instagramHandle: string;
  closeTime: string;
}

export interface Story {
  id: string;
  username: string;
  avatar: string;
  isBar: boolean;
  barName?: string;
  emoji: string;
  timestamp: string;
}

export const MOCK_BARS: Bar[] = [
  {
    id: '1',
    name: 'The Wharf Rat',
    neighborhood: 'Fells Point',
    vibe: 'Dive Bar',
    emoji: '🐀',
    color: '#1A0A2E',
    currentCrowd: 94,
    activeSpecial: '$2 Natty Boh drafts all night. Baltimore proud.',
    badgeEmoji: '🐀',
    badgeRarity: 'RARE',
    address: '801 S Ann St, Fells Point',
    instagramHandle: '@thewharfrat',
    closeTime: '2am',
  },
  {
    id: '2',
    name: 'Loco Hombre',
    neighborhood: 'Federal Hill',
    vibe: 'Bar & Grill',
    emoji: '🌮',
    color: '#2D0A0A',
    currentCrowd: 88,
    activeSpecial: 'Taco Tuesday — 3 tacos for $9 + margarita pitchers $18',
    badgeEmoji: '🌮',
    badgeRarity: 'COMMON',
    address: '413 W Hamburg St, Federal Hill',
    instagramHandle: '@locohombrebaltimore',
    closeTime: '2am',
  },
  {
    id: '3',
    name: 'Corks',
    neighborhood: 'Federal Hill',
    vibe: 'Wine Bar',
    emoji: '🍷',
    color: '#2D0A1A',
    currentCrowd: 72,
    activeSpecial: 'Half-price bottles of red every Wednesday',
    badgeEmoji: '🍷',
    badgeRarity: 'EPIC',
    address: '1096 Wells St, Federal Hill',
    instagramHandle: '@corksbaltimore',
    closeTime: '1am',
  },
  {
    id: '4',
    name: 'The Rotunda Pub',
    neighborhood: 'Hampden',
    vibe: 'Pub',
    emoji: '🏛️',
    color: '#0A1A2D',
    currentCrowd: 65,
    activeSpecial: 'Live trivia at 8pm — winner drinks free',
    badgeEmoji: '🏛️',
    badgeRarity: 'RARE',
    address: '711 W 40th St, Hampden',
    instagramHandle: '@rotundapub',
    closeTime: '2am',
  },
  {
    id: '5',
    name: 'Della Rose\'s',
    neighborhood: 'Federal Hill',
    vibe: 'Sports Bar',
    emoji: '🌹',
    color: '#2D0A2D',
    currentCrowd: 82,
    activeSpecial: 'Game night — $3 domestic beers during any Baltimore sports',
    badgeEmoji: '🌹',
    badgeRarity: 'COMMON',
    address: '1220 S Charles St, Federal Hill',
    instagramHandle: '@dellaroses',
    closeTime: '2am',
  },
  {
    id: '6',
    name: 'The Horse You Came In On',
    neighborhood: 'Fells Point',
    vibe: 'Historic Saloon',
    emoji: '🐴',
    color: '#1A1A0A',
    currentCrowd: 91,
    activeSpecial: 'Live blues band tonight — no cover',
    badgeEmoji: '🐴',
    badgeRarity: 'LEGENDARY',
    address: '1626 Thames St, Fells Point',
    instagramHandle: '@horseyoucameinon',
    closeTime: '2am',
  },
  {
    id: '7',
    name: 'Cat\'s Eye Pub',
    neighborhood: 'Fells Point',
    vibe: 'Live Music Bar',
    emoji: '😺',
    color: '#0A2D1A',
    currentCrowd: 78,
    activeSpecial: 'No cover before 9pm — jazz quartet performing',
    badgeEmoji: '😺',
    badgeRarity: 'EPIC',
    address: '1730 Thames St, Fells Point',
    instagramHandle: '@catseyepub',
    closeTime: '2am',
  },
  {
    id: '8',
    name: 'Bookmakers Cocktail Club',
    neighborhood: 'Mount Vernon',
    vibe: 'Cocktail Lounge',
    emoji: '📚',
    color: '#1A0A2D',
    currentCrowd: 68,
    activeSpecial: 'Literary cocktails — name a book, we make the drink',
    badgeEmoji: '📚',
    badgeRarity: 'RARE',
    address: '31 E Chase St, Mount Vernon',
    instagramHandle: '@bookmakersbaltimore',
    closeTime: '2am',
  },
  {
    id: '9',
    name: 'Brewer\'s Art',
    neighborhood: 'Mount Vernon',
    vibe: 'Brewpub',
    emoji: '🍺',
    color: '#2D1A0A',
    currentCrowd: 85,
    activeSpecial: 'Rotating craft taps — new IPA just tapped tonight',
    badgeEmoji: '🍺',
    badgeRarity: 'RARE',
    address: '1106 N Charles St, Mount Vernon',
    instagramHandle: '@brewersartbaltimore',
    closeTime: '2am',
  },
  {
    id: '10',
    name: 'Max\'s Taphouse',
    neighborhood: 'Fells Point',
    vibe: 'Beer Paradise',
    emoji: '🏺',
    color: '#0A2D2D',
    currentCrowd: 96,
    activeSpecial: '102 taps on — ask for the hidden reserve menu',
    badgeEmoji: '🏺',
    badgeRarity: 'LEGENDARY',
    address: '737 S Broadway, Fells Point',
    instagramHandle: '@maxstaphouse',
    closeTime: '2am',
  },
  {
    id: '11',
    name: 'Rye',
    neighborhood: 'Fells Point',
    vibe: 'Whiskey Bar',
    emoji: '🥃',
    color: '#2D1A0A',
    currentCrowd: 74,
    activeSpecial: 'Whiskey flight Friday — 4 pours for $22',
    badgeEmoji: '🥃',
    badgeRarity: 'EPIC',
    address: '807 S Broadway, Fells Point',
    instagramHandle: '@ryefellspoint',
    closeTime: '2am',
  },
  {
    id: '12',
    name: 'Ouzo Bay',
    neighborhood: 'Inner Harbor',
    vibe: 'Upscale Mediterranean',
    emoji: '🐟',
    color: '#0A1A2D',
    currentCrowd: 79,
    activeSpecial: 'Happy hour oysters — $2 each until 7pm',
    badgeEmoji: '🐟',
    badgeRarity: 'EPIC',
    address: '1000 Lancaster St, Inner Harbor',
    instagramHandle: '@ouzobay',
    closeTime: '1am',
  },
  {
    id: '13',
    name: 'Tiki Barge',
    neighborhood: 'Inner Harbor',
    vibe: 'Tiki Bar',
    emoji: '🌺',
    color: '#0A2D0A',
    currentCrowd: 87,
    activeSpecial: 'Rum punch bowl for 4 people — $35',
    badgeEmoji: '🌺',
    badgeRarity: 'RARE',
    address: 'Pier 5, Inner Harbor',
    instagramHandle: '@tikibarge',
    closeTime: '2am',
  },
  {
    id: '14',
    name: 'The 13th Floor',
    neighborhood: 'Downtown',
    vibe: 'Rooftop Lounge',
    emoji: '🌆',
    color: '#1A0A2D',
    currentCrowd: 83,
    activeSpecial: 'Skyline cocktails — panoramic city views all night',
    badgeEmoji: '🌆',
    badgeRarity: 'LEGENDARY',
    address: '1 E Baltimore St, Downtown',
    instagramHandle: '@13thfloorbaltimore',
    closeTime: '2am',
  },
  {
    id: '15',
    name: 'Midway Bar & Grill',
    neighborhood: 'Hampden',
    vibe: 'Neighborhood Bar',
    emoji: '🎪',
    color: '#2D2D0A',
    currentCrowd: 56,
    badgeEmoji: '🎪',
    badgeRarity: 'COMMON',
    address: '2549 N Howard St, Hampden',
    instagramHandle: '@midwayhampden',
    closeTime: '2am',
  },
  {
    id: '16',
    name: 'NV Lounge',
    neighborhood: 'Downtown',
    vibe: 'Nightclub',
    emoji: '💜',
    color: '#1A002D',
    currentCrowd: 92,
    activeSpecial: 'VIP tables available — DM for reservations',
    badgeEmoji: '💜',
    badgeRarity: 'EPIC',
    address: '10 Market Pl, Downtown',
    instagramHandle: '@nvloungebaltimore',
    closeTime: '3am',
  },
  {
    id: '17',
    name: 'Duda\'s Tavern',
    neighborhood: 'Fells Point',
    vibe: 'Old School Tavern',
    emoji: '🪑',
    color: '#1A0A0A',
    currentCrowd: 61,
    activeSpecial: 'Cash only — coldest Natty Boh in Charm City',
    badgeEmoji: '🪑',
    badgeRarity: 'COMMON',
    address: '1600 Thames St, Fells Point',
    instagramHandle: '@dudasbaltimore',
    closeTime: '2am',
  },
  {
    id: '18',
    name: 'One-Eyed Mike\'s',
    neighborhood: 'Fells Point',
    vibe: 'Bar & Music',
    emoji: '🏴‍☠️',
    color: '#0A0A2D',
    currentCrowd: 70,
    activeSpecial: 'Open mic night — sign up at the bar',
    badgeEmoji: '🏴‍☠️',
    badgeRarity: 'RARE',
    address: '708 S Bond St, Fells Point',
    instagramHandle: '@oneeyedmikes',
    closeTime: '2am',
  },
  {
    id: '19',
    name: 'Henninger\'s Tavern',
    neighborhood: 'Fells Point',
    vibe: 'German Tavern',
    emoji: '🥨',
    color: '#2D1A0A',
    currentCrowd: 58,
    activeSpecial: 'Schnitzel Thursday — half off all German entrees',
    badgeEmoji: '🥨',
    badgeRarity: 'COMMON',
    address: '1812 Bank St, Fells Point',
    instagramHandle: '@henningers',
    closeTime: '1am',
  },
  {
    id: '20',
    name: 'Power Plant Live!',
    neighborhood: 'Inner Harbor',
    vibe: 'Entertainment District',
    emoji: '⚡',
    color: '#2D2D00',
    currentCrowd: 89,
    activeSpecial: 'Multiple venues open — wristband gets you into 5 bars',
    badgeEmoji: '⚡',
    badgeRarity: 'LEGENDARY',
    address: '34 Market Pl, Inner Harbor',
    instagramHandle: '@powerplantlive',
    closeTime: '3am',
  },
];

// CCN BarData — used by BarCard, BarCardCompact, BadgeCard, CrowdMeter components
export const CCN_BARS: BarData[] = [
  { id: '1', name: 'The Horse You Came In On', neighborhood: 'Fells Point', vibe: 'Dive Bar', color: '#FF6B35', currentCrowd: 94, checkInsTonight: 247, activeSpecial: 'Free shot with any beer', emoji: '🐴', badgeEmoji: '🐎', badgeRarity: 'LEGENDARY', image: barImages.horseYouCameInOn },
  { id: '2', name: "Cat's Eye Pub", neighborhood: 'Fells Point', vibe: 'Live Music', color: '#7B2FBE', currentCrowd: 78, checkInsTonight: 183, activeSpecial: 'Live blues 9pm', emoji: '🐱', badgeEmoji: '🎵', badgeRarity: 'RARE', image: barImages.catsEyePub },
  { id: '3', name: 'Rec Pier Chophouse', neighborhood: 'Fells Point', vibe: 'Upscale', color: '#FFD700', currentCrowd: 65, checkInsTonight: 142, emoji: '⚓', badgeEmoji: '👑', badgeRarity: 'EPIC', image: barImages.recPier },
  { id: '4', name: 'Federal Hill Brewing', neighborhood: 'Federal Hill', vibe: 'Brewery', color: '#00C9A7', currentCrowd: 55, checkInsTonight: 98, activeSpecial: 'Pint night $4', emoji: '🍺', badgeEmoji: '🏭', badgeRarity: 'RARE', image: barImages.federalHillBrewing },
  { id: '5', name: 'Banditos', neighborhood: 'Federal Hill', vibe: 'Mexican Bar', color: '#FF3366', currentCrowd: 82, checkInsTonight: 201, activeSpecial: '$3 tacos till 11', emoji: '🌮', badgeEmoji: '🤠', badgeRarity: 'COMMON', image: barImages.banditos },
  { id: '6', name: 'No Way Jose', neighborhood: 'Federal Hill', vibe: 'Cantina', color: '#FF6B35', currentCrowd: 71, checkInsTonight: 156, emoji: '🌵', badgeEmoji: '🍹', badgeRarity: 'COMMON', image: barImages.noWayJose },
  { id: '7', name: "Moe's Tavern Canton", neighborhood: 'Canton', vibe: 'Sports Bar', color: '#3B82F6', currentCrowd: 88, checkInsTonight: 312, activeSpecial: 'All games on, $5 pitchers', emoji: '🏈', badgeEmoji: '🍻', badgeRarity: 'COMMON', image: barImages.cantonSocial },
  { id: '8', name: 'The Anchor', neighborhood: 'Canton', vibe: 'Dive Bar', color: '#4ECDC4', currentCrowd: 45, checkInsTonight: 67, emoji: '⚓', badgeEmoji: '🪝', badgeRarity: 'RARE', image: barImages.rustyAnchor },
  { id: '9', name: 'Power Plant Live', neighborhood: 'Inner Harbor', vibe: 'Club/Venue', color: '#FFD700', currentCrowd: 96, checkInsTonight: 578, activeSpecial: 'Free entry before 10', emoji: '⚡', badgeEmoji: '🔌', badgeRarity: 'LEGENDARY', image: barImages.powerPlantLive },
  { id: '10', name: 'Lure', neighborhood: 'Inner Harbor', vibe: 'Rooftop Bar', color: '#8B5CF6', currentCrowd: 73, checkInsTonight: 189, activeSpecial: 'Sunset hour ends 8pm', emoji: '🌆', badgeEmoji: '🦅', badgeRarity: 'EPIC', image: barImages.federalRooftop },
  { id: '11', name: 'Maximón', neighborhood: 'Mount Vernon', vibe: 'Latin Club', color: '#FF3366', currentCrowd: 85, checkInsTonight: 234, activeSpecial: 'Salsa night 10pm', emoji: '💃', badgeEmoji: '🌺', badgeRarity: 'EPIC', image: barImages.maximon },
  { id: '12', name: "The Brewer's Art", neighborhood: 'Mount Vernon', vibe: 'Craft Beer', color: '#7B2FBE', currentCrowd: 62, checkInsTonight: 134, emoji: '🎨', badgeEmoji: '🖼️', badgeRarity: 'RARE', image: barImages.brewersArt },
  { id: '13', name: 'Ottobar', neighborhood: 'Charles Village', vibe: 'Indie Rock', color: '#FF3366', currentCrowd: 79, checkInsTonight: 167, activeSpecial: 'Local band 9pm, $8 cover', emoji: '🎸', badgeEmoji: '🤟', badgeRarity: 'RARE', image: barImages.ottobar },
  { id: '14', name: 'Club Charles', neighborhood: 'Charles Village', vibe: 'Dive/Art Bar', color: '#9CA3AF', currentCrowd: 48, checkInsTonight: 89, emoji: '🎭', badgeEmoji: '🃏', badgeRarity: 'COMMON', image: barImages.clubCharles },
  { id: '15', name: 'Golden West Cafe', neighborhood: 'Hampden', vibe: 'Bar/Cafe', color: '#FFD700', currentCrowd: 38, checkInsTonight: 54, emoji: '🌻', badgeEmoji: '🤠', badgeRarity: 'COMMON', image: barImages.goldenWest },
  { id: '16', name: 'The Dizz', neighborhood: 'Hampden', vibe: 'Neighborhood Bar', color: '#00C9A7', currentCrowd: 52, checkInsTonight: 91, emoji: '🌀', badgeEmoji: '😵‍💫', badgeRarity: 'COMMON', image: barImages.theDizz },
  { id: '17', name: 'Union Craft Brewing', neighborhood: 'Medfield', vibe: 'Taproom', color: '#FF6B35', currentCrowd: 67, checkInsTonight: 148, activeSpecial: 'New IPA release tonight', emoji: '🏭', badgeEmoji: '🤝', badgeRarity: 'RARE', image: barImages.unionCraft },
  { id: '18', name: 'Wet City', neighborhood: 'Mount Vernon', vibe: 'Craft Beer', color: '#3B82F6', currentCrowd: 44, checkInsTonight: 76, emoji: '💧', badgeEmoji: '🌊', badgeRarity: 'RARE', image: barImages.wetCity },
  { id: '19', name: 'Sticky Rice', neighborhood: 'Inner Harbor East', vibe: 'Asian Fusion Bar', color: '#FF3366', currentCrowd: 71, checkInsTonight: 163, activeSpecial: 'Happy hour till 9', emoji: '🍣', badgeEmoji: '🥢', badgeRarity: 'COMMON', image: barImages.stickyRice },
  { id: '20', name: 'The Elk Room', neighborhood: 'Downtown', vibe: 'Speakeasy', color: '#F59E0B', currentCrowd: 58, checkInsTonight: 112, emoji: '🦌', badgeEmoji: '🕵️', badgeRarity: 'LEGENDARY', image: barImages.elkRoom },
];

export const CCN_STORIES = [
  { id: 's1', username: 'jmill_bmore', isViewed: false, isBar: false },
  { id: 's2', username: 'canton_kate', isViewed: false, isBar: false },
  { id: 's3', username: 'fells_frank', isViewed: true, isBar: false },
  { id: 's4', username: 'Power Plant', isViewed: false, isBar: true, barColor: '#FFD700' },
  { id: 's5', username: 'federal_b', isViewed: false, isBar: false },
  { id: 's6', username: "Cat's Eye", isViewed: true, isBar: true, barColor: '#7B2FBE' },
];

export const MOCK_STORIES: Story[] = [
  {
    id: 's1',
    username: 'ashley_bmore',
    avatar: '👩',
    isBar: false,
    emoji: '🍹',
    timestamp: '2h ago',
  },
  {
    id: 's2',
    username: 'MaxsTaphouse',
    avatar: '🏺',
    isBar: true,
    barName: "Max's Taphouse",
    emoji: '🍺',
    timestamp: '1h ago',
  },
  {
    id: 's3',
    username: 'mike_fellspt',
    avatar: '👨',
    isBar: false,
    emoji: '🎵',
    timestamp: '3h ago',
  },
  {
    id: 's4',
    username: 'TheHorsePub',
    avatar: '🐴',
    isBar: true,
    barName: 'The Horse You Came In On',
    emoji: '🎸',
    timestamp: '45m ago',
  },
  {
    id: 's5',
    username: 'sara_nightlife',
    avatar: '👩‍🦰',
    isBar: false,
    emoji: '🌙',
    timestamp: '30m ago',
  },
  {
    id: 's6',
    username: 'NVLounge',
    avatar: '💜',
    isBar: true,
    barName: 'NV Lounge',
    emoji: '🎉',
    timestamp: '15m ago',
  },
];
