import type { VaultItem } from '../types/vault';

// ─── Per-venue Vault items — "The Vault" hidden discovery layer ───────────────
// Each venue has 3–5 items: 1 midnight drop + 2–4 collectibles/codes/challenges

export const VAULT_ITEMS: VaultItem[] = [

  // ── Fells Point: The Horse You Came In On (id: '6') ──────────────────────
  {
    id: 'v-horse-1',
    venueId: '6',
    name: 'The Phantom Round',
    description: 'Show your bartender this screen and say "The Phantom" for a secret shot not on the menu. Changes monthly.',
    hint: 'A round that doesn\'t exist on paper. Ask the right way.',
    emoji: '🍸',
    rarity: 'LEGENDARY',
    type: 'secret_code',
    trigger: 'checkin',
    triggerLabel: 'Check in to unlock',
    isMidnightDrop: true,
    dropExpiresIn: '4d 6h',
    secretCode: 'THE PHANTOM',
  },
  {
    id: 'v-horse-2',
    venueId: '6',
    name: 'Old Mare Stamp',
    description: 'Stamped. You found the oldest bar in Baltimore. Edgar Allan Poe drank here. Now you have.',
    hint: 'Some stamps are older than the city itself.',
    emoji: '🐴',
    rarity: 'EPIC',
    type: 'stamp',
    trigger: 'checkin',
    triggerLabel: 'Check in to unlock',
    isMidnightDrop: false,
  },
  {
    id: 'v-horse-3',
    venueId: '6',
    name: 'Blues Lifer',
    description: 'Stay for at least one full blues set and prove it by completing this challenge.',
    hint: 'The music here has a history. Can you sit through it?',
    emoji: '🎸',
    rarity: 'RARE',
    type: 'challenge',
    trigger: 'challenge',
    triggerLabel: 'Complete the challenge',
    isMidnightDrop: false,
    challengeTask: 'Stay for a live blues performance and name the song playing when you unlock this.',
  },

  // ── Fells Point: Max's Taphouse (id: '10') ────────────────────────────────
  {
    id: 'v-maxs-1',
    venueId: '10',
    name: 'The Hidden Reserve',
    description: 'Ask for "Tap 103" — it\'s not on the board. Reserved for regulars and those who know.',
    hint: '102 taps you can see. One you can\'t.',
    emoji: '🏺',
    rarity: 'LEGENDARY',
    type: 'secret_code',
    trigger: 'streak_5',
    triggerLabel: 'Visit 5 times to unlock',
    isMidnightDrop: true,
    dropExpiresIn: '6d 2h',
    secretCode: 'TAP 103',
  },
  {
    id: 'v-maxs-2',
    venueId: '10',
    name: 'Hophead Passport',
    description: 'Certified: you\'ve sampled more beers here than most people know exist.',
    hint: 'You need receipts. Liquid receipts.',
    emoji: '🍺',
    rarity: 'RARE',
    type: 'stamp',
    trigger: 'streak_2',
    triggerLabel: 'Visit twice to unlock',
    isMidnightDrop: false,
  },
  {
    id: 'v-maxs-3',
    venueId: '10',
    name: 'Friend Finder',
    description: 'Unlock this only when a friend checks in the same night. No solo entry.',
    hint: 'Some doors only open for two.',
    emoji: '🤝',
    rarity: 'EPIC',
    type: 'collectible',
    trigger: 'friend_unlock',
    triggerLabel: 'Unlock with a friend',
    isMidnightDrop: false,
  },

  // ── Federal Hill: Loco Hombre (id: '2') ──────────────────────────────────
  {
    id: 'v-loco-1',
    venueId: '2',
    name: 'La Carta Negra',
    description: 'Order the "Carta Negra" — it\'s an off-menu tasting flight the bartender chooses for you. Trust it.',
    hint: 'There is a menu they don\'t print.',
    emoji: '🌮',
    rarity: 'EPIC',
    type: 'secret_code',
    trigger: 'checkin',
    triggerLabel: 'Check in to unlock',
    isMidnightDrop: true,
    dropExpiresIn: '2d 18h',
    secretCode: 'CARTA NEGRA',
  },
  {
    id: 'v-loco-2',
    venueId: '2',
    name: 'Federal Passport Stamp',
    description: 'You made it to the Hill. Stamped and registered.',
    hint: 'The Hill has its own rules.',
    emoji: '⛰️',
    rarity: 'COMMON',
    type: 'stamp',
    trigger: 'checkin',
    triggerLabel: 'Check in to unlock',
    isMidnightDrop: false,
  },

  // ── Mount Vernon: Brewer's Art (id: '9') ──────────────────────────────────
  {
    id: 'v-brew-1',
    venueId: '9',
    name: 'The Basement Drop',
    description: 'The basement bar has a rotating "dark shelf" — ask for what\'s not listed. Say "What\'s in the dark?"',
    hint: 'The best things here aren\'t upstairs.',
    emoji: '🕯️',
    rarity: 'LEGENDARY',
    type: 'secret_code',
    trigger: 'checkin',
    triggerLabel: 'Check in to unlock',
    isMidnightDrop: true,
    dropExpiresIn: '1d 9h',
    secretCode: 'WHAT\'S IN THE DARK',
  },
  {
    id: 'v-brew-2',
    venueId: '9',
    name: 'Craft Pilgrim',
    description: 'You found the Art. Most tourists never make it past the ground floor.',
    hint: 'The converted mansion has many floors.',
    emoji: '🎨',
    rarity: 'RARE',
    type: 'stamp',
    trigger: 'checkin',
    triggerLabel: 'Check in to unlock',
    isMidnightDrop: false,
  },
  {
    id: 'v-brew-3',
    venueId: '9',
    name: 'Thursday Night Ghost',
    description: 'Only unlockable Thursday nights after midnight. The after-midnight crowd knows something.',
    hint: 'Night owls only. Wrong night? Come back.',
    emoji: '👻',
    rarity: 'EPIC',
    type: 'collectible',
    trigger: 'time_window',
    triggerLabel: 'Thursday after midnight only',
    isMidnightDrop: false,
  },

  // ── Inner Harbor: Power Plant Live (id: '20') ─────────────────────────────
  {
    id: 'v-ppl-1',
    venueId: '20',
    name: 'The Wristband Override',
    description: 'Flash this screen at the PPL info booth to ask about the "Inner Circle" after-party access.',
    hint: 'There\'s a level above the wristband.',
    emoji: '⚡',
    rarity: 'LEGENDARY',
    type: 'mystery_box',
    trigger: 'streak_5',
    triggerLabel: 'Visit 5 times to unlock',
    isMidnightDrop: true,
    dropExpiresIn: '5d 0h',
  },
  {
    id: 'v-ppl-2',
    venueId: '20',
    name: 'Harbor Nomad',
    description: 'You move between venues like you own the waterfront.',
    hint: 'Check in at 3 Inner Harbor spots in one night.',
    emoji: '🌊',
    rarity: 'RARE',
    type: 'stamp',
    trigger: 'challenge',
    triggerLabel: 'Check in at 3 Harbor spots in one night',
    isMidnightDrop: false,
    challengeTask: 'Check into 3 different Inner Harbor venues in a single night.',
  },

  // ── Mount Vernon: Bookmakers Cocktail Club (id: '8') ──────────────────────
  {
    id: 'v-book-1',
    venueId: '8',
    name: 'The First Edition',
    description: 'Tell your bartender the name of a book, any book. They\'ll build you a cocktail inspired by it. Off-menu, never repeated.',
    hint: 'The menu here is in your mind.',
    emoji: '📚',
    rarity: 'LEGENDARY',
    type: 'secret_code',
    trigger: 'checkin',
    triggerLabel: 'Check in to unlock',
    isMidnightDrop: true,
    dropExpiresIn: '7d 0h',
    secretCode: 'NAME A BOOK',
  },
  {
    id: 'v-book-2',
    venueId: '8',
    name: 'Literary Pilgrim',
    description: 'Stamped. The cocktail club recognizes a fellow reader of the city.',
    hint: 'Not everyone finds this block.',
    emoji: '🖋️',
    rarity: 'EPIC',
    type: 'stamp',
    trigger: 'checkin',
    triggerLabel: 'Check in to unlock',
    isMidnightDrop: false,
  },
];

// Helper: get vault items for a venue
export function getVaultItems(venueId: string): VaultItem[] {
  return VAULT_ITEMS.filter((item) => item.venueId === venueId);
}

// Mock pre-unlocked items (for demo)
export const MOCK_UNLOCKED_IDS = new Set([
  'v-horse-2',
  'v-maxs-2',
  'v-brew-2',
  'v-book-2',
]);
